public enum Material
{
    Air
    , Grass
    , Dirt
    , Stone
    , Cobblestone
    , Bedrock
    , Oak_Log
    , Oak_Leaves
    , Structure_Block
    , Tall_Grass
    , Red_Flower
    , Coal_Ore
    , Iron_Ore
    , Lapis_Ore
    , Gold_Ore
    , Redstone_Ore
    , Diamond_Ore
    , Water
    , Lava
    , Sand
    , Sandstone
    , Gravel
    , Oak_Planks
    , Stick
    , Wooden_Pickaxe
    , Wooden_Axe
    , Wooden_Shovel
    , Wooden_Sword
    , Wooden_Hoe
    , Stone_Pickaxe
    , Stone_Axe
    , Stone_Shovel
    , Stone_Sword
    , Stone_Hoe
    , Iron_Pickaxe
    , Iron_Axe
    , Iron_Shovel
    , Iron_Sword
    , Iron_Hoe
    , Golden_Pickaxe
    , Golden_Axe
    , Golden_Shovel
    , Golden_Sword
    , Golden_Hoe
    , Diamond_Pickaxe
    , Diamond_Axe
    , Diamond_Shovel
    , Diamond_Sword
    , Diamond_Hoe
    , Crafting_Table
    , Furnace
    , Coal
    , Iron_Ingot
    , Gold_Ingot
    , Redstone_Dust
    , Diamond
    , Torch
    , Chest
    , Cactus
    , Fire
    , Raw_Chicken
    , Cooked_Chicken
    , Oak_Plank_Stairs
    , Wooden_Trapdoor
    , Wooden_Door
    , Wooden_Door_Top
    , Wooden_Door_Bottom
    , Wool_Block
    , Bed_Bottom
    , Bed_Top
    , Bed
    , Dead_Bush
    , Birch_Log
    , Mossy_Cobblestone
    , Wheat_Seeds
    , Wheat
    , Farmland_Dry
    , Farmland_Wet
    , Wheat_Crop
    , Ladder
    , Obsidian
    , Flint
    , Flint_And_Steel
    , Portal_Frame
    , Netherrack
    , TNT
    , Raw_Beef
    , Steak
    , Raw_Porkchop
    , Cooked_Porkchop
    , Rotten_Flesh
    , Bread
    , Gunpowder
    , Glass
    , Painting
    , Bone
    , Empty_Bucket
    , Water_Bucket
    , Lava_Bucket
    , Jukebox
    , Music_Disc_Stal
    , Wipe
    , Oak_Sapling
    , Cobweb
    , Melon_Slice
    , Melon
    , Melon_Seeds
    , Melon_Crop
    , Sign
    , Birch_Sapling
    , Birch_Leaves
    , Nether_Bricks
}